// Copyright (c) Facebook, Inc. and its affiliates.
pub const SOURCES: [&str; 20] = [
    include_str!("index.rd"),
    include_str!("intro.rd"),
    include_str!("intro.pre-bench.rd"),
    include_str!("intro.iocost.rd"),
    include_str!("intro.hashd.rd"),
    include_str!("intro.post-bench.rd"),
    include_str!("intro.sysreqs.rd"),
    include_str!("comp.cgroup.rd"),
    include_str!("comp.cgroup.mem.rd"),
    include_str!("comp.cgroup.mem.thrash.rd"),
    include_str!("comp.cgroup.io.rd"),
    include_str!("comp.cgroup.cpu.rd"),
    include_str!("comp.psi.rd"),
    include_str!("comp.oomd.rd"),
    include_str!("prot.demo.rd"),
    include_str!("side.intro.rd"),
    include_str!("side.sideloader.rd"),
    include_str!("side.details.rd"),
    include_str!("side.exp.rd"),
    include_str!("doc-format.rd"),
];
