# Copyright (c) Facebook, Inc. and its affiliates.

name: Build & test

on:
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cargo Build
        run: cargo build

      - name: Cargo Test
        run: cargo test
